services:
  mc-server:
    image: eclipse-temurin:17-jre
    container_name: ${CONTAINER_NAME}
    user: "${USER_ID}:${GROUP_ID}"
    restart: always
    volumes:
      - .:/data
    working_dir: /data
    ports:
      - "${MC_PORT}:25565"
      - "${VOICE_PORT}:54454/udp"
    stdin_open: true
    tty: true
    entrypoint: /bin/bash
    command: ./start.sh
    deploy:
      resources:
        limits:
          memory: ${MEM_LIMIT}